sudo: required

arch:
#  repos:
#    - papyros=http://dash.papyros.io/repos/$repo/$arch
  packages:
    # pacman packages
    - base
    - base-devel 
    - iw
    - wpa_supplicant
    - dialog
    - network-manager-applet
    - networkmanager
    - bind-tools
    - cmake
    - bash
    - bash-completion
    - qt5-base
    - qt5-doc
    - qt5-tools
    - boost
    - boost-libs
    - db
    - pkg-config
    - openssl
    - miniupnpc
    - qrencode
    - libuv
    - libmicrohttpd
    - zeromq
    - unbound
    - libunwind
    - xz
    - readline
    - curl
    - ldns
    - expat
    - gtest
    - doxygen
    - graphviz
    # aur packages
    # - go-git
    # packages from papyros repo
#    - papyros-shell
script:
  - "./build_script.sh"

script:
  - "curl -s https://raw.githubusercontent.com/jackl0phty/arch-travis/master/arch-travis.sh | bash"

notifications:
webhooks: https://galaxy.ansible.com/api/v1/notifications/
