---
# tasks file for jackl0phty.arch_linux
- hosts: all
  tasks:
  # Include playbook variables.
  - name: Include playbook vars.
    include_vars: '../../vars/main.yml'

  # Install Arch Linux Kubernetes packages.
  - name: Install Kubernetes packages for Arch Linux.
    pacman:
      name: "{{ item }}"
      state: present
    with_items: '{{ kubernetes_packages }}'
    become: yes
    become_user: root
    when: ansible_distribution == "Archlinux"

  # Record if Docker is running.
  - shell: "netstat -nlp |grep docker |/usr/bin/egrep -v grep |/usr/bin/awk '{print $7 }'"
    register: docker
    ignore_errors: True 
    
  # Start Docker service.
  - name: Start Docker service.
    command: systemctl start docker.socket
    when: docker == 'LISTENING'
    become: yes
    become_user: root

  # Has Docker been enabled at boot.
  - name: Has Docker been enabled on boot.
    shell: "systemctl list-unit-files |grep docker.socket |awk '{ print $2 }'"
    register: docker_enabled
    ignore_errors: True

  # Enable Docker on boot.
  - name: Enable Docker on boot.
    shell: systemctl enable --now docker.socket
    when: docker_enabled == 'disabled'
    args:
    become: yes
    become_user: root

