---
# tasks file for jackl0phty.arch_linux
- hosts: all
  vars:
  tasks:
  # Include playbook variables.
  - name: Include playbook vars.
    include_vars: '../vars/main.yml'

  # Install NVIDIA GPU driver.
  - name: Install NVIDIA GPU driver.
    pacman:
      name: nvidia
      state: present

  # Add maintainer GPG key to install ncurses5-compat-libs.
  - name: Confirm GPG key has been imported.
    command: gpg2 --list-keys |grep 702353E0F7E48EDB |awk '{ print $1 }'
    register: gpg_key_id
    ignore_errors: True
    become: yes
    become_user: root

  # Print out value of gpg_key_id.
  # Uncomment to DEBUG.
  #- name: Print out value of gpg_key_id.
  #  debug:
  #    var: gpg_key_id
  #    verbosity: 2 

  # Import gpg key of package maintainer.
  - name: Import gpg key of maintainer.
    command: gpg --keyserver keys.gnupg.net --recv-keys 702353E0F7E48EDB
    when: gpg_key_id|failed
    become: yes
    become_user: root

  # Write out yaourt config file.
  - name: write out yaourt config file.
    template:
      src: '../templates/yaourt.j2'
      dest: "{{ nvidia_user_home_dir }}/.yaourtrc"
      owner: "{{ nvidia_user }}"
      group: "{{ nvidia_user }}"
      mode: 0644
    become: yes
    become_user: root

  # Install ncurses5-compat-libs via yaourt.
  - name: Install ncurses5-compat-libs via yaourt.
    shell:  'gpg --keyserver keys.gnupg.net --recv-keys 702353E0F7E48EDB && export VISUAL=vim && yaourt --noconfirm -S ncurses5-compat-libs'
    when: gpg_key_id|failed
    become: yes
    become_user: '{{ nvidia_user }}'


  # Install NVIDIA CUDA GPU Driver & tools.
  - name: Install NVIDIA CUDA GPU Driver & tools for Arch Linux.
    pacman:
      name: "{{ item }}"
      state: present
    with_items: '{{ nvidia_cuda_gpu_packages }}'
    become: yes
    become_user: root
    when: ansible_distribution == "Archlinux"

  
  
