---

- hosts: all
  tasks:

  # Include playbook variables.
  - name: Include playbook vars
    include_vars: '../vars/main.yml'

  # Install packages for pipenv.
  - name: Install pipenv packages.
    pacman:
      name: "{{ item }}"
      state: present
    with_items: '{{ pipenv_packages }}'
    become: yes
    become_user: root
    when: ansible_distribution == "Archlinux"

  # Install pipenv via pip Ansible module.
  - name: Install pipenv via pip Ansible module.
    pip:
      name: pipenv 
    become: yes
    become_user: root
    when: ansible_distribution == "Archlinux"
