---
# tasks file for jackl0phty.arch_linux
- hosts: all
  tasks:
  # Include playbook variables.
  - name: Include playbook vars.
    include_vars: '../vars/main.yml'

  # Install Arch Linux stats graphing stack packages.
  - name: Install graphing stack packages for Arch Linux.
    pacman:
      name: "{{ item }}"
      state: present
    with_items: '{{ stats_graphing_stack_packages }}'
    become: yes
    become_user: root
    when: ansible_distribution == "Archlinux"

  # Clone StatsD Github repo.
  - name: Clone StatsD Github repo.
    git:
      repo: "{{ statsd_git_repo }}"
      dest: "{{ statsd_clone_dir }}"
      version: "{{ statsd_git_branch }}"
      force: yes
      update: yes
    become: yes
    become_user: root

  # Set perms to to un-priv user.
  - name: Set perms on StatsD repo to un-priv user.
    file:
      path: "{{ statsd_clone_dir }}"
      owner: "{{ statsd_user }}"
      group: "{{ statsd_user }}"
      state: directory
      mode: 0755
      recurse: yes
    become: yes
    become_user: root

  # Record if CollectD is running.
  - shell: "/usr/bin/ps aux |/usr/bin/grep 'collectd -f' |/usr/bin/egrep -v grep |/usr/bin/awk '{print $11 }'"
    register: collectd
    ignore_errors: True 

 
  # Start CollectD service.
  - name: Start CollectD service.
    command: systemctl start collectd.service
    when: collectd == 'collectd'
    become: yes
    become_user: root
 
  # Has Collectd been enabled at boot.
  - name: Has CollectD been enabled on boot.
    shell: "systemctl list-unit-files |grep collectd.service |awk '{ print $2 }'"
    register: collectd_enabled
    ignore_errors: True

  # Enable CollectD on boot.
  - name: Enable CollectD on boot.
    shell: systemctl enable --now collectd.service
    args:
    become: yes
    become_user: root

  # Has Grafana been enabled at boot.
  - name: Has Grafana been enabled on boot.
    shell: "systemctl list-unit-files |grep grafana.service |awk '{ print $2 }'"
    register: grafana_enabled
    ignore_errors: True
  
  # Enable Grafana on boot. 
  - name: Enable Grafana on boot.
    shell: "systemctl enable --now grafana.service"
    args:
    become: yes
    become_user: root
