---
# tasks file for jackl0phty.arch_linux
- hosts: all
  tasks:
  # Include playbook variables.
  - name: Include playbook vars.
    include_vars: '../../vars/main.yml'

  # Install Arch Linux Grafana plugin packages.
  - name: Install Grafana plugin packages for Arch Linux.
    pacman:
      name: "{{ item }}"
      state: present
    with_items: '{{ grafana_plugins_packages }}'
    become: yes
    become_user: root
    when: ansible_distribution == "Archlinux"

  # Has histogram Grafana plugin been installed.
  - name: Has histogram Grafana plugin been installed. 
    stat: path=/var/lib/grafana/plugins/mtanda-histogram-panel/package.json
    register: histogram_install
    become: yes
    become_user: root

  # Install histogram Grafana plugin.
  - name: Install histogram Grafana plugin.
    shell: grafana-cli plugins install mtanda-histogram-panel; systemctl restart grafana.service
    args:
    when: histogram_install.stat.exists == False
    become: yes 
    become_user: root
